[project]
name = "fuzzy-clust-regression"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "federated-clustering @ git+https://github.com/stallmo/federated_clustering",
    "matplotlib>=3.10.7",
    "notebook>=7.5.0",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "flwr[simulation]>=1.24.0",
    "flwr-datasets>=0.5.0",
    "pytest>=9.0.2",
    "wandb>=0.23.1",
    "optuna>=4.6.0",
]
